/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

uint8_t DDRB = 0;


#define BIT_SET(REG,BIT_NUMBER)		REG |= 1U<<BIT_NUMBER
#define BIT_CLEAR(REG,BIT_NUMBER)	REG &=~ (1U<<BIT_NUMBER)

int main(void)
{
	//uint8_t a = 0xA0;	//0b1010 0000 <> 160 -> 160
	//a = a | 0xA;		//0b1010 0000 | 0b100 -> 0b1010 0100
	/*establecer*/
	BIT_SET(DDRB,2);
	printf("DDRB->0x%X\n",DDRB);
	DDRB |= 1U<<3 | 1U<<7;
	printf("DDRB->0x%X\n",DDRB);
	/*CLEAR*/
	//DDRB &=~ (1U<<7 | 1U<<2);
	BIT_CLEAR(DDRB,7);
	printf("DDRB->0x%X\n",DDRB);
	/*COMPLEMENTO*/
	DDRB ^= 1U<<3;
	printf("DDRB->0x%X\n",DDRB);
	DDRB ^= 1U<<3;
	printf("DDRB->0x%X\n",DDRB);
	/*NEGACION BIT A BIT*/
	DDRB = ~DDRB;
	printf("DDRB->0x%X\n",DDRB);
    /* Loop forever */
	for(;;);
}
