/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


#define SMRAM_BASE   	0x20000000
#define RCC_BASE	 	0x40023800
#define GPIOA_BASE		0x40020000

uint32_t data;
uint32_t *ptrData;

int main(void)
{
	ptrData = &data;

	*((volatile uint32_t*)(0x20000080)) = 10;

	printf("valor de data->%d\r\n",data);
	printf("direccion de mem->0x%x\r\n",ptrData);
/******************************************************/
	volatile uint32_t *RCC_AHB1ENR;
	volatile uint32_t *GPIOA_MODER;
	volatile uint32_t *GPIOA_ODR;


	RCC_AHB1ENR = (volatile uint32_t*)(RCC_BASE + 0x30);
	GPIOA_MODER = (volatile uint32_t*)(GPIOA_BASE);
	GPIOA_ODR = (volatile uint32_t*)(GPIOA_BASE + 0x14);


	*RCC_AHB1ENR = 0x1;
	*GPIOA_MODER |= 0x400;
	*GPIOA_ODR = 0x20;




    /* Loop forever */
	for(;;);
}
