/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


extern void ITM_SendChar(uint8_t ch);


int main(void)
{
	puts("!!!Hello World!!!");
    /* Loop forever */
	for(;;);
}


int __io_putchar(int ch){

	uint8_t c = ch & 0xFF;
	ITM_SendChar(c);
	return ch;
}
